# Default values for helm_nginx.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

namespace: default

metadata:
  name: nginx-ingress-controller
  labels:
    name: ingress-nginx
    partof: ingress-nginx

prometheus:
  port: 10254
  scrape: true

image:
  repository: quay.io/kubernetes-ingress-controller/nginx-ingress-controller 
  tag: 0.26.1
  pullPolicy: IfNotPresent

container:
  name: nginx-ingress-controller
  args:
    - /nginx-ingress-controller
    - --configmap=$(POD_NAMESPACE)/nginx-configuration
    - --tcp-services-configmap=$(POD_NAMESPACE)/tcp-services
    - --udp-services-configmap=$(POD_NAMESPACE)/udp-services
    - --publish-service=$(POD_NAMESPACE)/ingress-nginx
    - --annotations-prefix=nginx.ingress.kubernetes.io
  drop:
    - ALL
  add:
    - NET_BIND_SERVICE
  privilege: true # to run with privilege escalation. This is to avoid security policy error. Make it false to remove this.
  user: 33
  ports:
    protocol: TCP
    name:
      http: 80
      https: 443
  liveness:
    failurethreshold: 3
    httpGet:
      path: /healthz
      port: 10254
      scheme: HTTP
    initialdelay: 10 # in seconds
    period: 10 # in seconds
    successthreshold: 1
    timeout: 10 # in seconds
  readiness:
    failurethreshold: 3
    httpGet:
      path: /healthz
      port: 10254
      scheme: HTTP
    # initialdelay: 10 # in seconds
    period: 10 # in seconds
    successthreshold: 1
    timeout: 10
  command:
    - /wait-shutdown


serviceaccount:
  name: default


# imagePullSecrets: []
# nameOverride: ""
# fullnameOverride: ""

# service:
#   type: ClusterIP
#   port: 80

# ingress:
#   enabled: false
#   annotations: {}
#     # kubernetes.io/ingress.class: nginx
#     # kubernetes.io/tls-acme: "true"
#   hosts:
#     - host: chart-example.local
#       paths: []

#   tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: 
    terminationperiod: 300
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector:
  os: linux

tolerations: []

affinity: {}
