apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx
  namespace: default
  labels:
    app.kubernetes.io/name: {{ .Values.metadata.labels.name }}
    app.kubernetes.io/part-of: {{ .Values.metadata.labels.partof }}
spec:
  type: NodePort
  ports:
    - name: http
      port: {{ .Values.container.ports.name.http }}
      targetPort: {{ .Values.container.ports.name.http }}
      protocol: {{ .Values.container.ports.protocol }}
    - name: https
      port: {{ .Values.container.ports.name.https }}
      targetPort: {{ .Values.container.ports.name.https }}
      protocol: {{ .Values.container.ports.protocol }}
  selector:
    app.kubernetes.io/name: {{ .Values.metadata.labels.name }}
    app.kubernetes.io/part-of: {{ .Values.metadata.labels.partof }}